use_default_settings: true

general:
  debug: false
  instance_name: "ArchCouncil Research"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  secret_key: "arch-council-local-only-change-me"
  limiter: false
  image_proxy: false
